POST http://localhost:5555/user
Content-Type: application/json
{
    "nome": "Hadna Jady",
    "email": "oliveirahadna@gmail.com"
}
###
GET  http://localhost:5555/user
###
GET http://localhost:5555/user/4
###
PUT  http://localhost:5555/user/2
Content-Type: application/json

{
    "name": "Maria Maria",
    "email": "nova@gmail.com"
}
###
DELETE  http://localhost:5555/user/2